# Generated by Django 4.0.3 on 2022-04-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_room_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
