# Generated by Django 4.0.3 on 2022-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.IntegerField(default=1)),
                ('room', models.CharField(choices=[('STANDARD', 'STANDARD'), ('EXECUTIVE', 'EXECUTIVE'), ('BUSINESS', 'BUSINESS'), ('PREMIUM', 'PREMIUM'), ('DELUXE', 'DELUXE'), ('PENTHOUSE', 'PENTHOUSE'), ('KING', 'KING')], max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
