# Generated by Django 4.0.3 on 2022-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_homebooking_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebooking',
            name='adults',
            field=models.IntegerField(),
        ),
    ]
