# Generated by Django 4.0.3 on 2022-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_homebooking_adults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebooking',
            name='adults',
            field=models.CharField(max_length=5),
        ),
    ]
