# Generated by Django 4.0.3 on 2022-05-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touch_name', models.CharField(max_length=50)),
                ('touch_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
